version: '3'

services:
  geth:
    image: ethereum/client-go:stable
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./geth-data:/root/ethereum
    command:
      - --datadir=/root/ethereum
      - --dev
      - --dev.period=1
      - --http
      - --http.addr=0.0.0.0
      - --ws
      - --ws.addr=0.0.0.0

  deploy:
    image: ghcr.io/worldcoin/hubble-commander:latest
    command: deploy --file /chain-spec/chain-spec.yaml
    environment:
      HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
      HUBBLE_ETHEREUM_CHAIN_ID: 1337
      HUBBLE_ETHEREUM_PRIVATE_KEY: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
    volumes:
      - chain-spec-volume:/chain-spec
    depends_on:
      - geth

  commander:
    image: ghcr.io/worldcoin/hubble-commander:latest
    restart: always
    environment:
      HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
      HUBBLE_ETHEREUM_CHAIN_ID: 1337
      HUBBLE_ETHEREUM_PRIVATE_KEY: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
      HUBBLE_BOOTSTRAP_CHAIN_SPEC_PATH: /chain-spec/chain-spec.yaml
      HUBBLE_BADGER_PATH: /db/data/hubble
      HUBBLE_LOG_LEVEL: debug
    ports:
      - 5000:8080
    volumes:
      - chain-spec-volume:/chain-spec
      - ./badger-data:/db/data/hubble
    depends_on:
      - geth

volumes:
  chain-spec-volume:
