[book]
language = "en"
multilingual = false
src = "docs"
title = "hubble-commander Documentation"

[build]
create-missing = false

[preprocessor.index]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4
