[package]
name = "worldcoin-hubble-commander"
version = "0.1.0"
authors = ["Dmytro Maretskyi <maretskii@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amcl = "0.2.0"
