#log:
#  level: info
#  format: text
#
#bootstrap:
#  prune: false
#  node_url: http://localhost:8080   # set this url to bootstrap from a remote node
#  chain_spec_path: chain-spec.yaml  # set this path to bootstrap from a chain spec file
#
#rollup:
#  sync_size: 50
#  fee_receiver_pub_key_id: 0
#  min_txs_per_commitment: 1
#  max_txs_per_commitment: 32
#  min_commitments_per_batch: 1
#  max_commitments_per_batch: 32
#  transfer_batch_submission_gas_limit: 400000
#  c2t_batch_submission_gas_limit: 500000
#  mm_batch_submission_gas_limit: 550000
#  deposit_batch_submission_gas_limit: 220000
#  transition_dispute_gas_limit: 4100000
#  signature_dispute_gas_limit: 7600000
#  batch_account_registration_gas_limit: 8000000
#  batch_loop_interval: 500ms
#
#api:
#  port: 8080
#  enable_proof_methods: false
#
#metrics:
#  port: 2112
#  endpoint: /metrics
#
#badger:
#  path: db/data/hubble
#
#ethereum:
#  rpc_url: ws://localhost:8546
#  chain_id: 1337
#  private_key: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
