bootstrap:
  bootstrap_node_url: http://localhost:8080   # remove this line to sync from blockchain

rollup:
  sync_size: 50
  fee_receiver_pub_key_id: 0
  txs_per_commitment: 32
  pending_txs_count_multiplier: 2
  min_commitments_per_batch: 1
  max_commitments_per_batch: 32
  commitment_loop_interval: 500ms
  batch_loop_interval: 500ms

api:
  port: 8080

postgres:
  host: localhost
  port: 5432
  name: hubble
  user: hubble
  password: root

badger:
  path: db/badger/data

ethereum:
  rpc_url: ws://localhost:8546
  chain_id: 1337
  private_key: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
