#log:
#  level: info
#  format: text
#
#bootstrap:
#  node_url: http://localhost:8080   # set this url to bootstrap from a remote node
#  chain_spec_path: chain-spec.yaml  # set this path to bootstrap from a chain spec file
#
#rollup:
#  sync_size: 50
#  fee_receiver_pub_key_id: 0
#  min_txs_per_commitment: 1
#  max_txs_per_commitment: 32
#  min_commitments_per_batch: 1
#  max_commitments_per_batch: 32
#  transition_dispute_gas_limit: 5000000
#  signature_dispute_gas_limit: 7500000
#  commitment_loop_interval: 500ms
#  batch_loop_interval: 500ms
#
#api:
#  port: 8080
#
#postgres:
#  host: localhost
#  port: 5432
#  name: hubble
#  user: hubble
#  password: root
#
#badger:
#  path: db/badger/data/hubble
#
#ethereum:
#  rpc_url: ws://localhost:8546
#  chain_id: 1337
#  private_key: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
