rollup:
  sync_batches: true
  fee_receiver_pub_key_id: 0
  txs_per_commitment: 32
  min_commitments_per_batch: 1
  max_commitments_per_batch: 32
  commitment_loop_interval: 500ms
  batch_loop_interval: 500ms
  block_number_loop_interval: 500ms
api:
  version: 0.0.1
  port: "8080"
postgres:
  dbhost: localhost
  dbname: hubble
  dbuser: hubble
  dbpassword: root
ethereum:
  rpc_url: ws://localhost:8545
  private_key: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
  chain_id: "1616067554748"
