version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=hubble
      - POSTGRES_PASSWORD=root

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@domain.com
      - PGADMIN_DEFAULT_PASSWORD=root
