version: '3'

services:
  geth:
    image: ethereum/client-go
    container_name: hubble-geth
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./e2e/geth-data:/root/ethereum
    command:
      - --datadir=/root/ethereum
      - --dev
      - --dev.period=1
      - --http
      - --http.addr=0.0.0.0
      - --ws
      - --ws.addr=0.0.0.0
