apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: hubble-commander
  name: hubble-commander
  namespace: production
data:
  HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
  HUBBLE_ETHEREUM_CHAIN_ID: "1337"
  HUBBLE_POSTGRES_HOST: consumer-app-crypto-db-production.cluster-c1amkrvabwaw.us-east-1.rds.amazonaws.com
  HUBBLE_POSTGRES_PORT: "5432"
  HUBBLE_BOOTSTRAP_CHAIN_SPEC_PATH: "/chain-spec/chain-spec.yaml"
  HUBBLE_ROLLUP_TXS_PER_COMMITMENT: "1"
  HUBBLE_ROLLUP_MIN_COMMITMENTS_PER_BATCH: "1"
  HUBBLE_LOG_LEVEL: "debug"
  HUBBLE_LOG_FORMAT: "json"
