version: '3'

services:
  geth-init:
    image: ethereum/client-go:stable
    volumes:
      - geth-data-volume:/root/ethereum
      - ./geth-keystore:/root/keystore
      - ./genesis:/root/genesis
    command:
      - --datadir=/root/ethereum
      - --keystore=/root/keystore
      - init
      - /root/genesis/worldcoin.json

  geth:
    image: ethereum/client-go:stable
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - geth-data-volume:/root/ethereum
      - ./geth-keystore:/root/keystore
    command:
      - --datadir=/root/ethereum
      - --keystore=/root/keystore
      - --unlock=0x8933394714873724b97a518533a974b3263b1a79
      - --password=~/.keystore-password
      - --mine
      - --http
      - --http.addr=0.0.0.0
      - --ws
      - --ws.addr=0.0.0.0

  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hubble
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    ports:
      - 5433:5433
    command: -p 5433

  deploy:
    image: ghcr.io/worldcoin/hubble-commander:latest-0.4.0
    command: deploy --file /chain-spec/chain-spec.yaml
    environment:
      HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
      HUBBLE_ETHEREUM_CHAIN_ID: 967532646 # "worldcoin" typed on mobile phone keypad
    env_file: ~/.private-key.env
    volumes:
      - chain-spec-volume:/chain-spec
    depends_on:
      - geth

  commander:
    image: ghcr.io/worldcoin/hubble-commander:latest-0.4.0
    restart: always
    environment:
      HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
      HUBBLE_ETHEREUM_CHAIN_ID: 967532646
      HUBBLE_BOOTSTRAP_CHAIN_SPEC_PATH: /chain-spec/chain-spec.yaml
      HUBBLE_POSTGRES_HOST: postgres
      HUBBLE_POSTGRES_PORT: 5433
      HUBBLE_POSTGRES_USER: root
      HUBBLE_POSTGRES_PASSWORD: password
      HUBBLE_POSTGRES_NAME: hubble
      HUBBLE_BADGER_PATH: /db/data/hubble
      HUBBLE_LOG_LEVEL: debug
    env_file: ~/.private-key.env
    ports:
      - 5000:8080
    volumes:
      - chain-spec-volume:/chain-spec
      - badger-data-volume:/db/data/hubble
    depends_on:
      - postgres
      - geth

volumes:
  geth-data-volume:
  postgres-data-volume:
  chain-spec-volume:
  badger-data-volume:
