image:
  image: "ghcr.io/worldcoin/hubble-commander"
  tag: # Defaults to `v` + appVersion
  arch: amd64 # Either amd64 or arm64
  pullSecret:

labels:
  component: # Defaults to name
  partOf: protocol-signup
  createdBy:

environment: prod
replicas: 1
region: "us-east-1"

canary:
  enabled: false

resources:
  requests:
    cpu: 1
    memory: 1024Mi
  limits:
    cpu: 16.0
    memory: 4Gi

# Env values can be strings (to be prefixed with `value:`) or objects
env:
  HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
  HUBBLE_ETHEREUM_CHAIN_ID: 1337
  HUBBLE_ETHEREUM_PRIVATE_KEY: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
  HUBBLE_BOOTSTRAP_CHAIN_SPEC_PATH: /chain-spec/chain-spec.yaml

# Spec ingress policy for the `api` and `metrics` port.
# Values are a list of NetworkPolicyPeer v1 objects, empty means allow all.
ingress:
  host: "crypto.stage-crypto.worldcoin.dev"
  api:
  metrics:
