version: '3'

services:
  geth:
    image: ethereum/client-go:stable
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - geth-data-volume:/root/ethereum
      - ./geth-keystore:/root/keystore
    command:
      - --datadir=/root/ethereum
      - --keystore=/root/keystore
      - --dev
      - --dev.period=1
      - --http
      - --http.addr=0.0.0.0
      - --ws
      - --ws.addr=0.0.0.0

  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hubble
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    ports:
      - 5433:5433
    command: -p 5433

  deploy:
    image: ghcr.io/worldcoin/hubble-commander:latest-0.4.0
    command: deploy --file /chain-spec/chain-spec.yaml
    environment:
      HUBBLE_BOOTSTRAP_BLOCKS_TO_FINALISE: 1209600 # 2 weeks on network with 1s block time
      HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
      HUBBLE_ETHEREUM_CHAIN_ID: 1337
      HUBBLE_ETHEREUM_PRIVATE_KEY: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
    volumes:
      - chain-spec-volume:/chain-spec
    depends_on:
      - geth

  commander:
    image: ghcr.io/worldcoin/hubble-commander:latest-0.4.0
    restart: always
    environment:
      HUBBLE_ETHEREUM_RPC_URL: ws://geth:8546
      HUBBLE_ETHEREUM_CHAIN_ID: 1337
      HUBBLE_ETHEREUM_PRIVATE_KEY: ee79b5f6e221356af78cf4c36f4f7885a11b67dfcc81c34d80249947330c0f82
      HUBBLE_BOOTSTRAP_CHAIN_SPEC_PATH: /chain-spec/chain-spec.yaml
      HUBBLE_POSTGRES_HOST: postgres
      HUBBLE_POSTGRES_PORT: 5433
      HUBBLE_POSTGRES_USER: root
      HUBBLE_POSTGRES_PASSWORD: password
      HUBBLE_POSTGRES_NAME: hubble
      HUBBLE_BADGER_PATH: /db/data/hubble
      HUBBLE_LOG_LEVEL: debug
    ports:
      - 5000:8080
    volumes:
      - chain-spec-volume:/chain-spec
      - badger-data-volume:/db/data/hubble
    depends_on:
      - postgres
      - geth

  backup:
    build:
      context: .
    init: true
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - chain-spec-volume:/root/chain-spec
      - badger-data-volume:/root/badger
      - geth-data-volume:/root/geth
      - ./../scripts:/root/scripts

volumes:
  geth-data-volume:
  postgres-data-volume:
  chain-spec-volume:
  badger-data-volume:
