{{ if .Values.wipeDisk }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ebs-wipe
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: hubble-storage
          persistentVolumeClaim:
            claimName: {{ include "hubble.fullname" . }} # same storage as Statefulset
      containers:
        - name: disk-wiper
          image: busybox
          command: ["rm", "-rf", "/volume/*"]
          volumeMounts:
            - name: hubble-storage
              mountPath: "/volume"
{{ end }}
