apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}-headless
  labels:
    {{- include "hubble.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      name: http
  clusterIP: None
  selector:
    {{- include "hubble.selectorLabels" . | nindent 4 }}
