apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: geth
  name: geth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/geth.logs: '[{"source":"go","service":"geth"}]'
        ad.datadoghq.com/tags: '{"env":"production"}'
    spec:
      containers:
        - name: geth
          image: "ethereum/client-go"
          command: ["/bin/sh"]

          args: [
            "-c",

            "echo \"Creating the cipher file...\" &&
            mkdir -p /root/ethereum/keystore &&
            echo '{\"address\":\"9f758331b439c1b664e86f2050f2360370f06849\",\"crypto\":{\"cipher\":\"aes-128-ctr\",\"ciphertext\":\"e1860e27080f7c6e7353cd132ae498b889d045849aa3f224d470d5d97ea09fc4\",\"cipherparams\":{\"iv\":\"3626816e04320eaa4bd4a7626787e839\"},\"kdf\":\"scrypt\",\"kdfparams\":{\"dklen\":32,\"n\":262144,\"p\":1,\"r\":8,\"salt\":\"34636cdd63c05f88c20632b5bdc312896125ec35e1b572a9c3276f75cab2408e\"},\"mac\":\"0a7edb666e831f892b06791da54c8d9ee61cbf0f99ab2ec03b6d812ee0ef334e\"},\"id\":\"db483d8e-2d98-490b-997e-26ed52ee6365\",\"version\":3}' | cat > /root/ethereum/keystore/UTC--2021-06-07T12-34-01.339648000Z--9f758331b439c1b664e86f2050f2360370f06849 &&
            geth --datadir=/root/ethereum --dev --dev.period=5 --http --http.addr=0.0.0.0 --ws --ws.addr=0.0.0.0",
          ]

          imagePullPolicy: Always
          ports:
            - containerPort: 8545
            - containerPort: 8546
          resources:
            requests:
              memory: "124Mi"
              cpu: "250m"
            limits:
              memory: "6144Mi"
              cpu: "1500m"
