DROP INDEX account_public_key_idx;
DROP INDEX commitment_included_in_batch_idx;
DROP INDEX transaction_base_from_state_id_idx;
DROP INDEX transaction_base_included_in_commitment_idx;
DROP INDEX batch_transaction_hash_idx;
