replicaCount: 1

environment: prod

image:
  repository: ghcr.io/worldcoin/hubble-commander
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true

securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
    drop:
      - all
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

service:
  type: ClusterIP
  port: 80

ingress:
  host: "hubble.crypto.worldcoin.dev"

resources:
  limits:
    cpu: 14
    memory: 30Gi
  requests:
    cpu: 8
    memory: 25Gi

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

persistentStorage:
  size: 100Gi
  volumeID: aws://us-east-1a/vol-041bb6e8b3bc69109 # example: aws://us-east-1c/vol-aabbcc123

wipeDisk: false
