name: Deploy stage contracts

on: workflow_dispatch

jobs:
  deploy-contracts:
    runs-on: ubuntu-latest
    environment: stage
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_STAGE_REGION }}
          role-to-assume: ${{ secrets.AWS_STAGE_ROLE }}
          role-duration-seconds: 900
      - name: Connect to EKS cluster
        run: aws eks update-kubeconfig
          --region ${{ secrets.AWS_STAGE_REGION }}
          --name ${{ secrets.AWS_STAGE_CLUSTER }}
      - name: Deploy contracts
        run: kubectl apply -n hubble-commander -f ./deploy/contracts-setup-job/clean-setup.yaml
