name: Hubble Commander CI
on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_USER: hubble
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      HUBBLE_DBUSER: hubble
      HUBBLE_DBPASSWORD: root
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Go dependencies
        run: make install
      - name: Generate bindings
        run: make generate
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: Build
        run: make build
      - name: Test
        run: make test
