name: Release
on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Evaluate image tags
        id: evaluate-tags
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          if [[ $VERSION_TAG == *"rc"* ]]; then
            echo ::set-output name=IMAGE_TAGS::ghcr.io/worldcoin/hubble-commander:${VERSION_TAG}
          else
            echo ::set-output name=IMAGE_TAGS::ghcr.io/worldcoin/hubble-commander:${VERSION_TAG},ghcr.io/worldcoin/hubble-commander:stable
          fi
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.evaluate-tags.outputs.IMAGE_TAGS }}
